"""add foreign key of user into posts

Revision ID: 58942248a70d
Revises: 0922449fc330
Create Date: 2024-08-07 11:46:07.254056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58942248a70d'
down_revision = '0922449fc330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
